[package]
name = "fireblocks"
version = "0.1.0"
publish = false
authors = [
  "Holaplex <engineering@holaplex.com>",
]
edition = "2021"
description = "Holaplex Hub treasury service"
readme = "./README.md"
repository = "https://github.com/holaplex/hub-treasuries"
license = "AGPL-3.0-or-later"
keywords = ["hub", "holaplex", "web3"]
categories = ["cryptography::cryptocurrencies", "web-programming"]


[dependencies]
chrono = "0.4.23"
sha2 = "0.10.6"
anyhow = "1.0.68"
hex = "0.4.3"
serde = { version = "1.0.152", features = ["derive"] }
jsonwebtoken = "8.2.0"
reqwest = { version = "0.11.13", features = ["json"] }
clap = { version = "4.0.32", features = ["derive", "env"] }
serde_with = "2.1.0"
serde_json = "1.0.91"
log = "^0.4.17"
tokio = { version = "1.23.0", features = ["full"] }
async-graphql = { version = "5.0.4", features = ["chrono", "uuid", "log", "dataloader", "apollo_tracing"] }