name: Release Image
on:
  push:
    branches:
      - mpw/ci-test
jobs:
  release:
    runs-on: self-hosted
    environment: release
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      -
        name: Build and push hub-treasuries
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          target: hub-treasuries
          push: true
          build-args: |
            ENVIRONMENT=stage
          tags: ${{ vars.DOCKERHUB_ORG }}/hub-treasuries:${{ github.sha }},${{ vars.DOCKERHUB_ORG }}/hub-treasuries:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push hub-treasuries-migrations
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          target: migrator
          push: true
          tags: ${{ vars.DOCKERHUB_ORG }}/hub-treasuries-migrations:${{ github.sha }},${{ vars.DOCKERHUB_ORG }}/hub-treasuries-migrations:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
